[package]
name = "ssg"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ssg"
path = "src/main.rs"

[dependencies]
tera = "1.20.1"
toml = "0.9.8"
serde_json = "1.0.145"
serde = { version = "1", features = ["derive"] }
jotdown = "0.9.0"