content_dir = "content"
public_dir = "public"
main_title = "Will Wang"

[page.home]
sub_title = ""
filename = "index.dj"

[page.now]
sub_title = "Now"
filename = "now.dj"

[thread.project_euler_note]
sub_title = "Project Euler Note"
path = "euler"

[thread.archive]
sub_title = "Archive"
path = "archive"
